apiVersion: v1
kind: Service

metadata:
  name: swe304-pro4-service

spec:
  type: NodePort

  selector:
    app: swe304-pro4

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
